name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: "true"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust with sccache
        uses: ./.github/actions/setup-rust-sccache
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      
      - name: Build
        run: cargo build --verbose --all-features
      
      - name: Run tests
        run: cargo test --verbose --all-features
      
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
        if: matrix.rust == 'stable'
      
      - name: Format check
        run: cargo fmt -- --check
        if: matrix.rust == 'stable'
      
      - name: Show sccache statistics
        run: sccache --show-stats
        if: always()

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust with sccache
        uses: ./.github/actions/setup-rust-sccache
        with:
          toolchain: stable
      
      - name: Build docs
        run: cargo doc --no-deps --all-features
      
      - name: Show sccache statistics
        run: sccache --show-stats
        if: always()

